#!/usr/bin/env node
// scripts/bulk-pdf.mjs
// Generate tailored PDFs for many reports at once.
//
// Usage:
//   node scripts/bulk-pdf.mjs                     # all reports in ./reports
//   node scripts/bulk-pdf.mjs --min 4.0           # only reports scoring ≥ 4.0
//   node scripts/bulk-pdf.mjs --reports a.md b.md # specific reports
//   node scripts/bulk-pdf.mjs --concurrency 1     # how many PDFs in parallel
//
// Each PDF is generated by spawning the existing generate-pdf.mjs as a child
// process. That keeps the bulk runner simple and means any improvement to the
// per-PDF logic propagates automatically.

import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { paths, c, parseArgs } from './lib/util.mjs';

const args = parseArgs();

async function main() {
  const reportsDir = paths.reports || './reports';
  if (!fs.existsSync(reportsDir)) {
    console.error(c.red(`No reports directory at ${reportsDir}.`));
    process.exit(1);
  }

  // Build the list of reports to process
  let reports;
  if (args.flags.reports) {
    // Comma- or space-separated explicit list
    reports = String(args.flags.reports).split(/[,\s]+/).filter(Boolean);
  } else {
    reports = fs.readdirSync(reportsDir)
      .filter((f) => f.endsWith('.md'))
      .map((f) => path.join(reportsDir, f));
  }

  // Optional score filter
  const minScore = parseFloat(args.flags.min || '0');
  if (minScore > 0) {
    reports = reports.filter((rp) => {
      try {
        const head = fs.readFileSync(rp, 'utf8').slice(0, 800);
        const m = head.match(/\*\*Score:\*\*\s*([\d.]+)/);
        if (!m) return false;
        return parseFloat(m[1]) >= minScore;
      } catch { return false; }
    });
  }

  if (reports.length === 0) {
    console.log(c.yellow('  No reports to process.'));
    if (minScore > 0) console.log(c.dim(`  (filter: score ≥ ${minScore})`));
    process.exit(0);
  }

  const concurrency = Math.max(1, parseInt(args.flags.concurrency || '1', 10));

  console.log(c.bold(`\nBulk PDF generation\n`));
  console.log(c.dim(`  reports:     ${reports.length}`));
  console.log(c.dim(`  concurrency: ${concurrency}`));
  if (minScore > 0) console.log(c.dim(`  min score:   ${minScore}`));
  console.log('');

  // Process in batches of `concurrency`. Local LLMs are usually GPU-bound, so
  // running 5 PDFs in parallel rarely helps and may make each one slower.
  // Default concurrency is 1, which is the safest.
  const queue = [...reports];
  const stats = { ok: 0, fail: 0, total: reports.length };

  async function worker(id) {
    while (queue.length) {
      const reportPath = queue.shift();
      const idx = stats.total - queue.length;
      const baseName = path.basename(reportPath);
      console.log(c.cyan(`  [${idx}/${stats.total}] ${baseName}`));
      try {
        await runPdf(reportPath);
        stats.ok++;
        console.log(c.dim(`              done`));
      } catch (err) {
        stats.fail++;
        console.log(c.red(`              FAIL: ${err.message}`));
      }
    }
  }

  const workers = Array.from({ length: concurrency }, (_, i) => worker(i + 1));
  await Promise.all(workers);

  console.log('');
  console.log(c.bold(`Done: ${c.green(stats.ok + ' ok')}, ${stats.fail ? c.red(stats.fail + ' failed') : c.dim('0 failed')}.`));
  console.log(c.dim(`PDFs in: ${paths.output || './output'}`));
  console.log('');
}

function runPdf(reportPath) {
  return new Promise((resolve, reject) => {
    const proc = spawn(process.execPath, ['scripts/generate-pdf.mjs', '--report', reportPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: process.env,
    });
    let stderr = '';
    let stdout = '';
    proc.stderr.on('data', (d) => { stderr += d.toString(); });
    proc.stdout.on('data', (d) => { stdout += d.toString(); });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(stderr.trim().split('\n').pop() || stdout.trim().split('\n').pop() || `exit ${code}`));
    });
  });
}

main().catch((err) => {
  console.error(c.red(`\nError: ${err.message}\n`));
  if (process.env.DEBUG) console.error(err.stack);
  process.exit(1);
});
